owner: Archtec-io
repo: statuspage
user-agent: Archtec-io

sites:
  #- name: Archtec
  #  url: "http://niklp.net"
  #  port: 30803
  #  check: "udp-ping" # doesn't exist :\
  - name: Mapserver
    url: https://archmap.niklp.net/
    expectedStatusCodes:
      - 503
  - name: Website
    url: https://archtec.niklp.net/
  - name: Matterbridge (Chatbridge)
    url: http://niklp.net
    port: $MATTERBRIDGE_PORT

status-website:
  baseUrl: /statuspage
  logoUrl: https://raw.githubusercontent.com/Archtec-io/statuspage/master/favicon.ico
  theme: night
  name: Archtec statuspage
  introTitle: "Statuspage of the **Archtec** minetest server. Main website [https://archtec.niklp.net](https://archtec.niklp.net/)"
  robotsText: "User-agent: * \n Disallow: /"
  navbar:
    - title: Status
      href: /
    - title: Archtec website
      href: https://archtec.niklp.net/

i18n:
  footer: Powered by [Upptime](https://upptime.js.org)
