owner: Archtec-io
repo: statuspage
user-agent: Archtec-io

sites:
  - name: Archtec
    url: "https://archtec.niklp.net/atcheck"
    icon: https://raw.githubusercontent.com/Archtec-io/statuspage/master/archtec.png
    maxResponseTime: 5000
  - name: Mapserver
    url: https://archmap.niklp.net/
    icon: https://raw.githubusercontent.com/Archtec-io/statuspage/master/archtec.png
    maxResponseTime: 5000
  - name: Website
    url: https://archtec.niklp.net/
    maxResponseTime: 5000
  - name: Matterbridge (Chatbridge)
    url: http://niklp.net
    port: $MATTERBRIDGE_PORT
    expectedStatusCodes:
      - 200
      - 403
    maxResponseTime: 5000
  - name: Freemyip (DynDns)
    url: https://freemyip.com/
    maxResponseTime: 5000
status-website:
  baseUrl: /statuspage
  logoUrl: https://raw.githubusercontent.com/Archtec-io/statuspage/master/archtec.png
  theme: night
  name: Archtec statuspage
  introMessage: "Statuspage of the **Archtec** minetest server. Main website [https://archtec.niklp.net](https://archtec.niklp.net/)"
  robotsText: "User-agent: * \n Disallow: /"
  navbar:
    - title: Status
      href: /
    - title: Archtec website
      href: https://archtec.niklp.net/

i18n:
  footer: Powered by [Upptime](https://upptime.js.org)
